sudo: required
services:
  - docker
language: go
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
before_script:
  - dockerfile="${VERSION}/Dockerfile"
  - dockertag="$VERSION"
  - true && [ "master" == "$TRAVIS_BRANCH" ] || dockertag="${TRAVIS_BRANCH}-${VERSION}"
script:
  - make deps
  - make build
  - make test
  - echo "* Building $DOCKER_IMAGE_NAME:$dockertag from $dockerfile"
  - docker build -t $DOCKER_IMAGE_NAME:$dockertag -f $dockerfile .
  - docker push $DOCKER_IMAGE_NAME:$dockertag
env:
  global:
    - secure: "m57q3qLQvrft5Esr9zVFwdNTb0tEjQ8gx2WCN9zC3XI4Pi+449UDr+tl1gUYAjhyCts2pK2ZHqnKf7IJpXM9la5AHEduCqFE20UwkbOad0EqhMyJf4zwq6zwph8lGEiZXi6leTWTL3m9YYgwvRLJkdmVcBe2YMOg64Qo3+GRF7LA3+gffdLQCW5PrxuN/misOWLZ1gfIYDlwKGbrwIWN3WyGtQ5EXFfimHpZVgWINNUmjiNYtTHylBLMLh5djwkPaSaAsZWMBbSEI2YNivp3RTmHCSY+vWrVwjavubWogvpkJcgCRpCFrMBQxC3EqVXI1bdgtDgUbRklYPwVKZ+YJcvT4XqQf3e8aGSY9VwesmFxLUQMPgIR8r6x7C5gM1JVttaMt0VoChIpOUw+CeImEVh/bqcPT79F/WfZTHeJupwypse0XKO+2ArIrRqFKZUScgFzXByG+tR0TI1IKn76wd3JxyOfMkeaJu4k0EBqA2yVOS/+KUoPZ1x8/cEmTCv+xqzIplmwrbAsUBcwsysqhqJPaTlqrRcjJEoicIIUQLcO2VFHkU/QOVUTovKfMHW2D4wvXR1MQCWF2oCEe99JTADGCMCZvNemmrAm0FPobb/dRiU96uZmU6fjO23EtcgcFmf0WMG2vS0HT9yutuXOBMDXHa7+CZ88TjSEGMEG1Eo="
    - DOCKER_IMAGE_NAME=glaszig/drone-capistrano
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  matrix:
    - VERSION=2.3
    - VERSION=2.4
    - VERSION=2.5
    - VERSION=2.6
    - VERSION=2.7
