sudo: required
services:
  - docker
language: go
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
before_script:
  - dockerfile="${VERSION}/Dockerfile"
  - dockertag="$VERSION"
  - true && [ "master" == "$TRAVIS_BRANCH" ] || dockertag="${TRAVIS_BRANCH}-${VERSION}"
script:
  - make deps
  - make build
  - make test
  - echo "* Building $DOCKER_IMAGE_NAME:$dockertag from $dockerfile"
  - docker build -t $DOCKER_IMAGE_NAME:$dockertag -f $dockerfile .
  - docker push $DOCKER_IMAGE_NAME:$dockertag
env:
  global:
    - secure: eigwgtJPj5grH/M4xKwFinh852nUo91mtYwKJzgxn89he6ATTsGlVO6x8jiOFMmJX0+9CBzcggRA2c4/nw720Me5FIv7M7SLvR4gBiVHDU5guDvIb634OwCIDlTtXPiAVeftRpM78JybohkFEEzmKMwX5gA1MYSlFBraydmSX4EtQBojavrur/+ofV6CE1xN6jGO3CBvWJ4ksokDJkklKMI5OWeBJiGACPGaRUX8xNNdl0an9eeQWlC1YMRngsxlrWQQcOtTAF7v55aSEqMFf5iWnFMAWPGS5IHxqD0A+cefDzgboCzof4RDK59Q18MD9i209WNCoi2GYn1imXvHyIwSvh5b7+03MXz+2pYE3p3sRCmOunjQ0m1y2lsRy3BFINyDvmfyuKBp5xU4qw51WkrwnzvjJxNeVXms67rW5ePWxhHJ21a7hm4kMhYs/yy9UPZ8VY6ECw53S8tRRHZT1p4wHytxWmtCSI0P2Dqyb/I2puzC7QqPs65IaO8Ygj30xCMU2sc3cgQ5VfavbtCUdEFLX/bPjiBL0nOMr97AfXSTmZd2Z4c7ebwVzen/F+7YbRzU7BD7zvt7bGt+HMjyrNkFJUT00wOz0Et0urf0KmvCRiQSrPwEvcV6HCZr/YxONNm16lqd2OT3svTqygdKsmVTw04bbD5PcyhUG530qQ8=
    - secure: TF8cHA4e4l2NqexCdYm75+91/i670FrSHHLyusl5P+YZUQWnqUw75Jn2rMe/nkkO+tbQwgkuAMNgMJn4gHo0XKXGPV7rxLSH7BerFVxPlbncfme+TWxk8N1Lmv6MxULpYTbQvNCjJDzWmobg9WEZ+7iLht39ibnNzImeqwl+2ak0JBTO9LExAAosPhQvzAJhwXQPuojge4sM4UhsByuUBf32w5qlwPhdCS3abn/cwvcLaWCUilrfo+pa7YKhfeVdHzlivNfMWoXU2O6Kgbym9fxKJ/KRVWhNfOu6xJxy+Lco750sRQIQHiy3YrOf7XrKMFI/r11QM1Vb9YbtxiWmKWRiVxW/uNFs5lMpfj4wnrYnobIyjEKxduBxkRoGVsLt0ZGHWv6Ae0RHT75e7Fw5BovCeRx4elj46xMnn4LJo2tVcRlqXpFhHvS308dxa4s+Cm1jCRXm045nNHPf4vcnuFKOqRc/9hawJcqFj7oC6PJZ10KTkhf9V1LZdG1X4SKXc4gkxxlbig9Ciu9fSjTJercGn/gdT9TP2iIgalGyizPYB5ovzSYdPEn+KML5FOF7cy2OWTj75KCbbUxW+pkyG/G0lzjBLaBvG+cM8lyDTJTuf8RIep+GxC8uzIpNQA+z+qNZPQ+tBU4VHqx5PFtAbEoMySFfDDoGKFIOobVDhSg=
    - DOCKER_IMAGE_NAME=glaszig/drone-capistrano
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  matrix:
    - VERSION=2.3
    - VERSION=2.4
    - VERSION=2.5
    - VERSION=2.6
    - VERSION=2.7
